### ISSUE TITLE
Clouds do not appear in the Better Clouds mod.

### ISSUE THREAD

**Issue by euSouzaah** [Qendolin/better-clouds#135] opened 2024-08-15 16:01 UTC
My Better Clouds mod is having some problems. Clouds only appear in areas that have blocks like those marked in the image. and there are no clouds in the sky.
I'm using translator to report this bug, if you don't understand what I wrote, this is why and I apologize
![image](https://github.com/user-attachments/assets/686796fd-a4f2-4c21-bb33-6cfc167ab809)

**Comment by Qendolin** [comment] 2024-08-15 23:50
This appears to be th same issue as https://github.com/Qendolin/better-clouds/issues/121 which is a driver issue probably. Can you send a screenshot of your f3 menu?

**Comment by euSouzaah** [comment] 2024-08-16 01:36
here it is
![image](https://github.com/user-attachments/assets/3d830f95-39c5-42db-bf38-7f442b495ec4)

**Comment by euSouzaah** [comment] 2024-08-16 23:18
I suspect it's not something related to the drivers, as they are all in the latest versions.

**Comment by Qendolin** [comment] 2024-08-16 23:33
It could be an issue with another mod but I think I've already ruled that out. I'm pretty sure its not a bug in the code.

**Comment by euSouzaah** [comment] 2024-08-16 23:34
I remember the same thing happened to me in Minecraft 1.20. Mod may not be the problem but something on my desktop

**Comment by Qendolin** [comment] 2024-08-17 19:17
I know it's one of two possible issues: Maybe the mod is doing something on the GPU that has undefined behavior or it's something that the GPU does incorrectly.

**Comment by euSouzaah** [comment] 2024-08-17 20:43
I use integrated graphics with the AMD Athlon 3000G processor, do you think this could be the case?

**Comment by Qendolin** [comment] 2024-08-17 20:59
Yes, I think others who had the same issues also used 3000 series AMD integrated GPU

**Comment by euSouzaah** [comment] 2024-08-17 21:09
So there's really nothing to do. AMD sometimes disappoints when it comes to graphics cards... thanks for your attention, Qendolin

**Comment by Qendolin** [comment] 2024-08-18 11:15
Duplicate of #121

**Closed by Qendolin** 2024-08-18 11:15 UTC
