### ISSUE TITLE
No clouds showing up and there are white boxes around blocks above the player

### ISSUE THREAD

**Issue by CryoLenced** [Qendolin/better-clouds#121] opened 2024-07-02 13:10 UTC
## Describe the bug
> No clouds are rendering after loading the world
> tried reloading resources or chunk reload didnt work
> white boxes tend to appear around blocks above the player that is facing the sky

## To Reproduce
> Steps to reproduce the behavior

1.  nothing really much to do as it happens as soon as i join the world
2. 
3. 
...

### Screenshots
> If applicable, add screenshots to help explain your problem.

### System Environment
- GPU: Radeon Vega 3 graphics, Radeon 540X series
- Mod Version:  1.7.0 for 1.21
- OS: Windows

*Optional*
- Shader:  none
- Other Mods: just fabric and yet another lib for better clouds to run

![2024-07-02_21 08 37](https://github.com/Qendolin/better-clouds/assets/174452798/15b49d1e-2fa2-46cd-8f5e-84286848570f)

**Comment by Qendolin** [comment] 2024-07-02 13:50
Seems like the same issue as #57.
Can you send a screenshot of the F3 menu and the latest.log file?

**Comment by CryoLenced** [comment] 2024-07-02 14:32
here they are, i hope it can be fixed
[latest.log](https://github.com/user-attachments/files/16070004/latest.log)
![2024-07-02_22 29 54](https://github.com/Qendolin/better-clouds/assets/174452798/04c4b172-0f2f-4ea4-a85b-c9056ea52cbc)

**Comment by Qendolin** [comment] 2024-07-02 14:45
Does the issue also happen without sodium?

**Comment by CryoLenced** [comment] 2024-07-02 14:50
yes still the same 
![2024-07-02_22 50 18](https://github.com/Qendolin/better-clouds/assets/174452798/77c00ee8-c7ed-4a99-8356-cc3dacda5cdf)

**Comment by CryoLenced** [comment] 2024-07-02 15:11
for some reasons they render somewhat but theyre only visible when looking between the blocks 
![2024-07-02_23 06 13](https://github.com/Qendolin/better-clouds/assets/174452798/5abdf042-9f30-4014-8c75-bcbc2232d371)
![2024-07-02_23 09 03](https://github.com/Qendolin/better-clouds/assets/174452798/58068a54-2e93-4bce-9e32-b2a3cb27ca4f)
![2024-07-02_23 09 10](https://github.com/Qendolin/better-clouds/assets/174452798/f8957135-170e-46a8-8510-bd680ba63ec7)

**Comment by Qendolin** [comment] 2024-07-02 16:27
I know this would be a little annoying, but can you go back to 1.20.x, confirm that the issue still occurs, then enable fabulous graphics and see if the issue goes away?

**Comment by CryoLenced** [comment] 2024-07-02 22:12
tried it on 1.20.6 it seems to fix the white boxes but clouds dont show and but theres now these blurryness on blocks they seem to be the clouds but not rendered properly
![2024-07-03_06 10 09](https://github.com/Qendolin/better-clouds/assets/174452798/07065d60-7180-4be0-9ddd-35da083d5812)

**Comment by Qendolin** [comment] 2024-07-02 22:21
Is that with fabulous graphics enabled?

**Comment by CryoLenced** [comment] 2024-07-02 22:36
Yes the fabulous graphic is enabled there

**Comment by Qendolin** [comment] 2024-07-02 22:45
[better-clouds-1.7.1-snapshot+1.21.rev.69210f6.zip](https://github.com/user-attachments/files/16074923/better-clouds-1.7.1-snapshot%2B1.21.rev.69210f6.zip)
The jar is inside the zip file. It's a custom release for 1.21 that *might* fix the issue.

**Comment by CryoLenced** [comment] 2024-07-02 23:02
it seems to have become better they're more visible but still just on blocks and not visible throughout the sky
![2024-07-03_06 59 37](https://github.com/Qendolin/better-clouds/assets/174452798/b4186595-01f1-4fbe-be9b-a400af30665c)
![2024-07-03_06 59 41](https://github.com/Qendolin/better-clouds/assets/174452798/304cd677-b0d3-4a24-8a4f-a48f72908e36)
![2024-07-03_07 00 04](https://github.com/Qendolin/better-clouds/assets/174452798/a6889467-26dd-4a0a-8633-8f86c228a707)
![2024-07-03_07 01 43](https://github.com/Qendolin/better-clouds/assets/174452798/daa4cce4-cc65-4e63-8c33-f2eb78b76032)

**Comment by Qendolin** [comment] 2024-07-02 23:22
[better-clouds-1.7.1-snapshot+1.21.rev.69210f6+1.zip](https://github.com/user-attachments/files/16075131/better-clouds-1.7.1-snapshot%2B1.21.rev.69210f6%2B1.zip)
Ok here is another one. If that doesn't work either then I'm out of ideas for now

**Comment by CryoLenced** [comment] 2024-07-02 23:42
it didnt work its the same as last still thanks for trying to fix it. Hope it gets fixed some time in the future

**Comment by Qendolin** [comment] 2024-08-19 11:43
Probably duplicate of #57

**Closed by Qendolin** 2024-08-19 11:43 UTC
Labels: bug, driver-issue

**Comment by CryoLenced** [comment] 2025-05-02 11:17
Hello i was able to fix this driver issue it seems that my laptop was using the integrated driver instead of the dedicated one. I just switched the graphics card it uses and it was working well now
