### ISSUE TITLE
Multiple Cloud Layers

### ISSUE THREAD

**Issue by Afrocntrik** [Qendolin/better-clouds#123] opened 2024-07-07 22:47 UTC
**Is your feature request related to a problem? Please describe.**
Another mod that tackles the cloud issue is [Elytra Aeronautics](https://modrinth.com/mod/elytra-aeronautics)

**Describe the solution you'd like**
Config options for additional clouds at specific y-layers

**Comment by Qendolin** [comment] 2024-07-07 22:56
Duplicate of #77 and #17

**Closed by Qendolin** 2024-07-07 22:56 UTC
Labels: enhancement
