### ISSUE TITLE
Large random magenta patterned cloud rendering issue

### ISSUE THREAD

**Issue by Wathfix** [Qendolin/better-clouds#133] opened 2024-08-12 20:00 UTC
![image](https://github.com/user-attachments/assets/30017b32-cc57-413a-97b9-e414105e480e)
idk what happends but all is purple and i cant see anything if i looking up

My pc is I5-3210m

intel graphics 4000

running without sodium because the game failed to start because the currently installed intel graphics driver is not compatible.

installed version 43.58
required version 10.18.10.5161 or newer
you must update your graphics card driver in order continue, i can update drivers but idk and im lazy maybe my pc is bad to run this mod or because old drivers

![image](https://github.com/user-attachments/assets/f825be6a-0c67-4c3a-99e0-4110ecbc2a0a)
theres my mods

**Comment by Qendolin** [comment] 2024-08-12 20:02
Yes this is a driver issue, an update might fix it, but on some gpus it's simply broken.

**Comment by Wathfix** [comment] 2024-08-12 20:31
![image](https://github.com/user-attachments/assets/62387084-4d03-4335-bcff-586be1117167)
i add sodium and i updated my drivers to last version from https://www.intel.com/content/www/us/en/products/sku/67355/intel-core-i53210m-processor-3m-cache-up-to-3-10-ghz-rpga/downloads.html

and theres still purple thing when im looking up

**Comment by Qendolin** [comment] 2024-08-12 20:53
I think you need [this tool](https://www.intel.com/content/www/us/en/support/detect.html) to properly update the drivers. If it still doesn't work afterwards then there isn't anything I can do.

**Comment by Qendolin** [comment] 2024-08-19 11:43
Probably duplicate of #69

**Closed as not planned by Qendolin** 2024-08-19 11:43 UTC
Labels: bug, duplicate, driver-issue
