### ISSUE TITLE
Game doesn't launch with Better Clouds

### ISSUE THREAD

**Issue by sanika48** [Qendolin/better-clouds#93] opened 2024-05-10 09:29 UTC
The game crashes while launching when using the newest version of Better Clouds (1.5.8).
"The game crashed whilst initializing game
Error: java.lang.ExceptionInInitializerError."
Newest Version of YACL (3.4.2) and Fabric API (0.97.8) is installed. Mod Menu is also present (10.0.0).
Crash log is attached.

[Crash Report.txt](https://github.com/Qendolin/better-clouds/files/15273119/Crash.Report.txt)

**Comment by Qendolin** [comment] 2024-05-10 12:32
Duplicate of #85

**Closed by Qendolin** 2024-05-10 12:32 UTC
Labels: bug
