### ISSUE TITLE
BetterClouds v1.5.8 crashes with MC1.20.5-6

### ISSUE THREAD

**Issue by Psora1** [Qendolin/better-clouds#90] opened 2024-05-03 15:13 UTC
## Description
> Provide a short description of the error

Game crashes on 1.20.6
### System Environment
- GPU: RTX 3080 Fe 10GB
- Mod Version: 1.5.8-1.20.4
- OS: Windows 11 Pro

*Optional:*
- Shader Pack: Complementary Reimagined 5.2 dev 9

### Game Log / Crash Report
> Add a link to your game log / crash report or attach it as a file

https://pastebin.com/yQaLUzfy

**Comment by Qendolin** [comment] 2024-05-03 16:39
Duplicate of #85

**Closed by Qendolin** 2024-05-03 16:39 UTC
Labels: bug
