### ISSUE TITLE
isn't launching😭

### ISSUE THREAD

**Issue by Mikkliish** [Qendolin/better-clouds#92] opened 2024-05-08 20:18 UTC
I'm launching with fabric in the normal minecraft launcher, and fabric api in my mods folder.
idk if i'm doing something wrong or what it is.
I am launching in 1.20.6 with the latest version of better clouds (1.20.4)

Whenever i launch it gives me this error which i don't really understand😅:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Better Clouds' (betterclouds) 1.5.8+1.20.4 with any version that is compatible with:
		 - Other constraints that can''t be automatically determined
More details:
	 - Mod 'Better Clouds' (betterclouds) 1.5.8+1.20.4 requires any version between 3.3.0 (inclusive) and 4- (exclusive) of yet_another_config_lib_v3, which is missing!

**Comment by Qendolin** [comment] 2024-05-08 20:33
Firstly you need YACL 3.4, you can get it on modrinth. Secondly >=1.20.5 is not supported, but might work

**Comment by Qendolin** [comment] 2024-05-10 12:31
Duplicate of #85

**Closed** 2024-05-10 12:32 UTC
